name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Trigger Jenkins job
      uses: toptal/jenkins-job-trigger-action@master
      with:
          jenkins_url: ${{ secrets.JENKINSURL }}
          jenkins_user: "jenkins"
          jenkins_token: ${{ secrets.JENKINSUSER }}
          job_name: ${{ secrets.JENKINSJOBNAME }}
          job_params: ${{ env.GITHUB_CONTEXT.head_ref }}
          job_timeout: "3600" # Default 30 sec. (optional)
