name: Java CI with Maven
on:
  pull_request:
    branches: [ main ]
jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
    - name: Get Branch Name
      run: |
        echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
        echo "{ \"Branch\":\"${GITHUB_HEAD_REF}\" }" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Trigger jenkins job
      uses: toptal/jenkins-job-trigger-action@master
      with:
          jenkins_url: ${{ secrets.JENKINSURL }}
          jenkins_user: "jenkins"
          jenkins_token: ${{ secrets.JENKINSUSER }}
          job_name: ${{ secrets.JENKINSJOBNAME }}
          job_params: ${{ env.JSON_RESPONSE }}
          job_timeout: "3600" # Default 30 sec. (optional)
